name: 'Upload Coverage Badge'
description: 'This actions requires an ApiGateway in AWS. Deploy the cdk stack in this repository first.'
inputs:
  total-coverage:
    description: "Coverage in percent [1-100]"
    required: true
  aws-api-key:
    description: "The api key of the AWS ApiGateway"
    required: true
  aws-api-url:
    description: "The api url of the AWS ApiGateway"
    required: true
outputs:
  url:
    description: "Url of resulting svg"
    value: ${{ steps.call-badge-api.outputs.url }}
runs:
  using: "composite"
  steps:
    - id: call-badge-api
      name: "Call Badge API"
      run: |
        github_ref=${{github.ref}}
        github_repository=${{github.repository}}
        echo {\"total_coverage\": ${{inputs.total-coverage}}, \
              \"project\": \"${github_ref##*/}\", \
              \"branch\": \"${github_repository##*/}\"} \
        >> data.json
        response=$(curl -s --request POST '${{inputs.aws-api-url}}' \
        --header 'x-api-key: ${{inputs.aws-api-key}}' \
        --header 'Content-Type: application/json' \
        -d @data.json)
        echo "::set-output name=url::$(echo $response | jq '.url')"
      shell: bash

